octomap_server:
  ros__parameters:
    map_while_grounded: true
    resolution: 0.4

    scope_timer:
      enabled: false
      file_name: "/tmp/scope_timer_trajectory_generation.txt"

    persistency:
      enabled: false
      map_name: "default"
      # save global map every "n" seconds, will be save only when flying_normally == true
      save_time: 10.0  # [s]
      align_altitude:
        enabled: false
        ground_detection_distance: 2.0  # [m]
        # how high is the fcu fram above the ground when sitting on the ground
        robot_height: 0.3  # [m]

    local_map:
      size:
        max_width: 30  # [m]
        max_height: 15  # [m]
        min_width: 20  # [m]
        min_height: 10  # [m]
        duty_high_threshold: 0.9
        duty_low_threshold: 0.8
      publisher_rate: 10.0  # [Hz]
      publish_full: true
      publish_binary: false

    global_map:
      size: 80  # [m]
      enabled: true
      publisher_rate: 1.0  # [Hz]
      creation_rate: 1.0  # [Hz]
      compress: true
      publish_full: true
      publish_binary: false

    # used only when subscribing 2D LaserScan, pointclouds have separate parameters for each sensor
    unknown_rays:
      update_free_space: true
      clear_occupied: false # beware, setting this to true is very dangerous
      ray_distance: 15.0

    # for point cloud raycasting
    sensor_params:
      3d_lidar:
        n_sensors: 1
        sensor_0:

          # fallback values used for free space raycasting for missing data, uses pointcloud dimensions from the incoming message by default
          max_range: 20.0  # [m]
          free_ray_distance: 15.0  # [m]
          vertical_fov_angle: deg(90)  # 90 degrees in radians
          vertical_rays: 128
          horizontal_rays: 128
          unknown_rays:
            update_free_space: true
            clear_occupied: false
            free_ray_distance_unknown: 0.2  # [m]
      depth_camera:
        n_sensors: 1
        sensor_0:
          max_range: 20.0  # [m]
          free_ray_distance: 15.0  # [m]
          horizontal_fov_angle: deg(70)  # 70 degrees in radians
          vertical_fov_angle: deg(35)  # 35 degrees in radians
          horizontal_rays: 80
          vertical_rays: 45
          unknown_rays:
            update_free_space: true
            clear_occupied: false
            free_ray_distance_unknown: 1.0  # [m]
      2d_lidar:
        n_sensors: 0
        # Example for sensor_0 (commented out)
        # sensor_0:
        #   max_range: 9.0  # [m]
        #   horizontal_rays: 40

    sensor_model:
      hit: 0.95   # [0, 1]
      miss: 0.45  # [0, 1]
      min: 0.3    # [0, 1]
      max: 0.7    # [0, 1]
