map_while_grounded: true

# resolution on the lowest level (fractor = 0, depth = max depth)
resolution: 0.05 # [m]

scope_timer:
  enabled: false
  file_name: "/tmp/scope_timer_trajectory_generation.txt"

persistency:

  enabled: false

  map_name: "default"

  # save mapevery "n" seconds, will be save only when flying_normally == true
  save_time: 10.0 # [s]

  # automatically aligns altitude after start
  align_altitude:

    enabled: false

    ground_detection_distance: 2.0 # [m]

    # how high is the fcu fram above the ground when sitting on the ground
    robot_height: 0.3 # [m]

local_map:

  # the bounding box distance of the local map
  size:
    width: 20 # [m]
    height: 10 # [m]

  # fractor = how many levels from the lowest level (the higherst res)
  #           should we work on
  # current_resolution = resolution * 2 ^ fractor
  initial_fractor: 3

  # the publisher rate of the local map
  publisher_rate: 10.0 # [Hz]

  publish_full: false # should publish map with full probabilities?
  publish_binary: true # should publish map with binary occupancy?

global_map:

  # should create a global map from the local map?
  enabled: true

  # the publisher rate of the global map
  publisher_rate: 1.0 # [Hz]

  # the rate of inserting the local map into the global map
  creation_rate: 1.0 # [Hz]

  # fractor = how many levels from the lowest level (the higherst res)
  #           should we work on
  # current_resolution = resolution * 2 ^ fractor
  initial_fractor: 3

  # should we prune the map before publishing?
  compress: true

  publish_full: false # should publish map with full probabilities?
  publish_binary: true # should publish map with binary occupancy?

unknown_rays:

  update_free_space: true
  clear_occupied: false # beware, setting this to true is very dangerous
  ray_distance: 15.0

# for point cloud raycasting
sensor_params:

  3d_lidar:

    n_sensors: 0

    # sensor_0:

    #   max_range: 20.0 # [m]

    #   vertical_fov_angle: deg(90.0)
    #   vertical_rays: 64
    #   horizontal_rays: 64

  depth_camera:

    n_sensors: 0

    # sensor_0:

    #   max_range: 9.0 # [m]

    #   horizontal_fov_angle: deg(70.0)
    #   vertical_fov_angle: deg(35.0)
    #   horizontal_rays: 80
    #   vertical_rays: 45

  2d_lidar:

    n_sensors: 0

    # sensor_0:

    #   max_range: 9.0 # [m]
    #   horizontal_rays: 40

sensor_model:

  hit: 0.95  # [0, 1]
  miss: 0.45 # [0, 1]
  min: 0.3  # [0, 1]
  max: 0.7  # [0, 1]
