resolution: 1.00
compress_map: true

main_timer:
  rate: 10 # [Hz]

unknown_rays:

  update_free_space: true
  ray_distance: 15.0

# for point cloud raycasting
sensor_params_3d:

  enabled: true
  vertical_fov_angle: deg(33.2)
  vertical_rays: 16
  horizontal_rays: 64 # default 2048

sensor_model:

  max_range: 40.0

  hit: 0.95  # [0, 1]
  miss: 0.45 # [0, 1]
  min: 0.3  # [0, 1]
  max: 0.7  # [0, 1]

local_mapping:
  enable: false
  distance: 30.0

nearby_clearing:
  enable: false
  distance: 1.0

visualization:

  free_throttled: 1.0 # [Hz]
  occupied_throttled: 1.0 # [Hz]

  occupancy:
    cube_size_factor: 1.0
    min_z: -1.79769e+308
    max_z: 1.79769e+308

  colored_map:
    enabled: false

  height_map:
    enabled: true
    color_factor: 0.8
    color:
      r: 1.0
      g: 0.0
      b: 0.0
      a: 1.0

  publish_free_space: true
  color_free:
    r: 0.0
    g: 1.0
    b: 0.0
    a: 1.0
