resolution: 1.00 # [m]

persistency:

  enabled: true

  map_name: "default"

  # save mapevery "n" seconds, will be save only when flying_normally == true
  save_time: 10.0 # [s]

global_map:

  # the publisher rate of the full map
  rate: 1.0 # [Hz]

  # should we prune the map before publishing?
  compress: true

  publish_full: true # should publish map with full probabilities?
  publish_binary: false # should publish map with binary occupancy?

local_map:

  # should create a local map from the global map?
  enabled: true

  # the bounding box distance of the local map
  distance: 50.0

  # the publisher rate of the local map
  rate: 10.0 # [Hz]

  publish_full: true # should publish map with full probabilities?
  publish_binary: false # should publish map with binary occupancy?

unknown_rays:

  update_free_space: true
  ray_distance: 15.0

# for point cloud raycasting
sensor_params_3d:

  enabled: true
  vertical_fov_angle: deg(33.2)
  vertical_rays: 16
  horizontal_rays: 64 # default 2048

sensor_model:

  max_range: 40.0

  hit: 0.95  # [0, 1]
  miss: 0.45 # [0, 1]
  min: 0.3  # [0, 1]
  max: 0.7  # [0, 1]
