resolution: 1.00
compress_map: true

update_free_space_using_missing_data: true

# for point cloud raycasting
sensor_params:

  enabled: true
  vertical_fov_angle: deg(45)
  vertical_rays: 16
  horizontal_rays: 2048

sensor_model:

  max_range: 40.0

  hit: 0.95  # [0, 1]
  miss: 0.45 # [0, 1]
  min: 0.05  # [0, 1]
  max: 0.95  # [0, 1]

filter_speckles: false

local_mapping:
  enable: false
  distance: 40.0

nearby_clearing:
  enable: false
  distance: 1.0

visualization:
  occupancy_min_z: -1.79769e+308
  occupancy_max_z: 1.79769e+308

  colored_map:
    enabled: false

  height_map:
    enabled: true
    color_factor: 0.8
    color:
      r: 1.0
      g: 0.0
      b: 0.0
      a: 1.0

  publish_free_space: true
  color_free:
    r: 0.0
    g: 1.0
    b: 0.0
    a: 1.0

  downprojected_2D_map:
    incremental_projection: false
    min_x_size: 30.0
    min_y_size: 30.0
