resolution: 0.20
frame_id: "uav1/stable_origin"
compress_map: true
update_free_space_using_missing_data: true

sensor_model:
  max_range: 14.0  #set to -1.0 for unlimited range
  hit: 0.9
  miss: 0.4
  min: 0.3
  max: 0.9

filter_speckles: false
ground_filter:
  enable: true
  distance: 0.6

local_mapping:
  enable: true 
  distance: 14.0

nearby_clearing:
  enable: true 
  distance: 0.4

visualization:
  occupancy_min_z: -1.79769e+308
  occupancy_max_z: 1.79769e+308

  colored_map:
    enabled: false

  height_map:
    enabled: true
    color_factor: 0.8
    color:
      r: 1.0
      g: 0.0
      b: 0.0
      a: 1.0

  publish_free_space: true
  color_free:
    r: 0.0
    g: 1.0
    b: 0.0
    a: 1.0

  downprojected_2D_map:
    incremental_projection: false
    min_x_size: 30.0
    min_y_size: 30.0
